### ISSUE TITLE
User should only vote once for each post.

### ISSUE THREAD

**Issue by Sahil624** [thecodinghub/news-for-good#3]
#### Right now one user can vote multiple time which should not be there.

My Suggestion is using Another table of voters with attributes
* Post Id
* voter name

and then search for the user for a particular post by post id if the user is there in the list of voter name then disable the voting buttons else the buttons will work.

**Comment by aj07** [comment]
Assign it to me

**Comment by Sahil624** [comment]
@aj07 Sure, I am assigning it to you. Do tell if you need any help.

**Comment by Sahil624** [comment]
Hi @aj07 !!!
I have seen that you have not replied to my message and not even forked this repo. So, can you please just leave an acknowledgment message, please.
Thanks 
Happy Coding.

**Comment by mdaizovi** [comment]
Instead of just incrementing votes, consider having a Many-to-many relationships between users and their upvotes or downvotes, then returning the distinct() count for the upvote/downvote number. Then you will accomplish what you want, counting the votes, without letting anyone do it more than once.
I started on this, but then since I wasn't sure if you wanted to allow people to upvote as well as downvote, or only one or the other, I did not continue. But you had some mistakes in the readme so I changed them and submitted a pull request. You model field "aurthor" is spelled wrong, but might be more trouble than it's worth to fix it? Up to you.

**Comment by Sahil624** [comment]
@mdaizovi Yup.I think it Is a better idea to use Many-to-many relationships.
A user should only vote once (either upvote or downvote) just like StackOverflow.
If you want to continue then you can just ping me once.
and about that spelling mistake, I think it is better to do at this stage.I will take care of it. 

PS:- Sorry for the late reply, I was out of town.

**Comment by mdaizovi** [comment]
You were right the first time re: new model w/ a 1:1 relationship, I don't know what I was thinking. I'm going to play with it right now and I'll submit a pull request when I'm done.

**Comment by Sahil624** [comment]
@mdaizovi Okay.Good Luck. :+1:

**Comment by Sahil624** [comment]
This Feature has been added by @mdaizovi.
Thanks Hope you will contribute more in future :+1: :100:
